import { QueryInterface } from 'sequelize';
import { v4 as uuidv4 } from 'uuid';

module.exports = {
    up: async (queryInterface: QueryInterface) => {
        await queryInterface.bulkInsert('jobs', [
            {
                description: 'Fix electrical wiring',
                title: 'Electrician Needed',
                seen: 0,
                approved: 1,
                mode: 'PHYSICAL',
                state: 'Lagos',
                lga: 'Ikeja',
                fullAddress: '123 Main Street, Ikeja',
                long: 3.3792,
                total: 50000,
                departureDaysCount: 2,
                arrivalDaysCount: 1,
                ownerLocationDeparture: JSON.stringify({ lat: 6.5244, lng: 3.3792 }),
                currentOwnerLocationDeparture: JSON.stringify({ lat: 6.5245, lng: 3.3793 }),
                currentOwnerLocationArrival: JSON.stringify({ lat: 6.5246, lng: 3.3794 }),
                currentClientLocationArrival: JSON.stringify({ lat: 6.5247, lng: 3.3795 }),
                currentClientLocationDeparture: JSON.stringify({ lat: 6.5248, lng: 3.3796 }),
                ownerLocationArrival: JSON.stringify({ lat: 6.5249, lng: 3.3797 }),
                clientLocation: JSON.stringify({ lat: 6.5250, lng: 3.3798 }),
                clientLocationArrival: JSON.stringify({ lat: 6.5251, lng: 3.3799 }),
                clientLocationDeparture: JSON.stringify({ lat: 6.5252, lng: 3.3800 }),
                isLocationMatch: 1,
                ownerMatchArrival: 1,
                clientMatchArrival: 0,
                clientMatchDeparture: 1,
                ownerMatchDeparture: 0,
                processed: 1,
                paid: 1,
                workmannShip: 30000,
                isMaterial: 1,
                gettingMaterial: 'Provided by owner',
                lan: 6.5244,
                durationUnit: 'days',
                reason: 'Routine maintenance',
                durationValue: 3,
                status: 'PENDING',
                ownerId: 'bfe391c2-a354-4e0f-9dd7-3afe6b5cffbd',
                userId: '4fdfb9dd-3a20-43dd-a387-a811ec6ba2ae',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                description: 'Plumbing work for kitchen',
                title: 'Plumber Required',
                seen: 1,
                approved: 1,
                mode: 'VIRTUAL',
                state: 'Abuja',
                lga: 'Garki',
                fullAddress: '456 Another Street, Garki',
                long: 7.4951,
                total: 75000,
                departureDaysCount: 1,
                arrivalDaysCount: 2,
                ownerLocationDeparture: JSON.stringify({ lat: 9.0578, lng: 7.4951 }),
                currentOwnerLocationDeparture: JSON.stringify({ lat: 9.0579, lng: 7.4952 }),
                currentOwnerLocationArrival: JSON.stringify({ lat: 9.0580, lng: 7.4953 }),
                currentClientLocationArrival: JSON.stringify({ lat: 9.0581, lng: 7.4954 }),
                currentClientLocationDeparture: JSON.stringify({ lat: 9.0582, lng: 7.4955 }),
                ownerLocationArrival: JSON.stringify({ lat: 9.0583, lng: 7.4956 }),
                clientLocation: JSON.stringify({ lat: 9.0584, lng: 7.4957 }),
                clientLocationArrival: JSON.stringify({ lat: 9.0585, lng: 7.4958 }),
                clientLocationDeparture: JSON.stringify({ lat: 9.0586, lng: 7.4959 }),
                isLocationMatch: 0,
                ownerMatchArrival: 0,
                clientMatchArrival: 1,
                clientMatchDeparture: 0,
                ownerMatchDeparture: 1,
                processed: 0,
                paid: 0,
                workmannShip: 45000,
                isMaterial: 0,
                gettingMaterial: 'Provided by client',
                lan: 9.0578,
                durationUnit: 'hours',
                reason: 'Leak repair',
                durationValue: 5,
                status: 'ONGOING',
                ownerId: 'cea9c359-e0be-44ce-9a21-209d68f63875',
                userId: 'bfe391c2-a354-4e0f-9dd7-3afe6b5cffbd',
                createdAt: new Date(),
                updatedAt: new Date()
            }
        ], {});
    },

    down: async (queryInterface: QueryInterface) => {
        await queryInterface.bulkDelete('jobs', {}, {});
    }
};
