import { QueryInterface } from 'sequelize';

export = {
    up: async (queryInterface: QueryInterface) => {
        await queryInterface.bulkInsert('professional', [
            {
                file: JSON.stringify({ certifications: ['Cert A', 'Cert B'] }),
                intro: 'Experienced software developer with a passion for problem-solving.',
                chargeFrom: 5000,
                language: JSON.stringify(['English', 'French']),
                avaialable: 1,
                workType: 'IDLE',
                totalJobCompleted: 10,
                totalJobCanceled: 2,
                totalReview: 8,
                totalJobPending: 3,
                totalJobOngoing: 1,
                totalJobRejected: 0,
                totalEarning: 50000,
                totalDispute: 1,
                completedAmount: 45000,
                pendingAmount: 3000,
                rejectedAmount: 0,
                availableWithdrawalAmount: 20000,
                regNum: 'PRO12345',
                yearsOfExp: '5 years',
                online: 1,
                userId: 'a44be52f-1408-4408-ba65-f43aae83aebb',
                corperateId: 1,
                profileId: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                file: JSON.stringify({ certifications: ['Cert C'] }),
                intro: 'Expert in data analysis and machine learning.',
                chargeFrom: 10000,
                language: JSON.stringify(['English']),
                avaialable: 1,
                workType: 'BUSY',
                totalJobCompleted: 20,
                totalJobCanceled: 1,
                totalReview: 15,
                totalJobPending: 2,
                totalJobOngoing: 3,
                totalJobRejected: 1,
                totalEarning: 150000,
                totalDispute: 0,
                completedAmount: 140000,
                pendingAmount: 5000,
                rejectedAmount: 1000,
                availableWithdrawalAmount: 70000,
                regNum: 'PRO67890',
                yearsOfExp: '8 years',
                online: 0,
                userId: '7ecba0d6-bee7-448d-9667-df59afc0e0c0',
                corperateId: 2,
                profileId: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                file: JSON.stringify({ certifications: ['Cert D', 'Cert E'] }),
                intro: 'Full-stack developer with expertise in cloud computing.',
                chargeFrom: 8000,
                language: JSON.stringify(['English', 'Spanish']),
                avaialable: 1,
                workType: 'IDLE',
                totalJobCompleted: 5,
                totalJobCanceled: 0,
                totalReview: 4,
                totalJobPending: 1,
                totalJobOngoing: 1,
                totalJobRejected: 0,
                totalEarning: 40000,
                totalDispute: 0,
                completedAmount: 35000,
                pendingAmount: 5000,
                rejectedAmount: 0,
                availableWithdrawalAmount: 15000,
                regNum: 'PRO11223',
                yearsOfExp: '3 years',
                online: 1,
                userId: 'f12f88d5-f1fa-4dc7-a98b-f5c8d87e76aa',
                corperateId: 3,
                profileId: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            }
        ]);
    },

    down: async (queryInterface: QueryInterface) => {
        await queryInterface.bulkDelete('professional', {});
    },
};
